"""
=============================================================================
Autonomous Fraud Detection & Response Network
Neo4j Graph Fraud Detection  +  Python Visualisation
=============================================================================

HOW IT WORKS  (full flow):
─────────────────────────────────────────────────────────────────────────────
  1. You supply ONE input file:
         synthetic_fraud_graph_dataset.csv
     (generated by generate_fraud_dataset.py)

  2. This script:
       a. Reads the CSV  →  your data source
       b. Pushes every row into Neo4j as a property graph
       c. Runs Cypher queries to find fraud patterns
       d. Pulls results back into Python
       e. Draws 6 visualisation charts and saves them as PNGs

  3. OUTPUT FILES produced:
       • neo4j_enriched_fraud_dataset.csv   (CSV with graph features)
       • viz_fraud_rings.png                (fraud ring subgraph)
       • viz_mule_chains.png                (mule chain paths)
       • viz_coordinated_hubs.png           (hub-and-spoke)
       • viz_shared_devices.png             (shared device clusters)
       • viz_risk_scores.png                (top risky accounts bar chart)
       • viz_full_fraud_network.png         (combined fraud subgraph)

─────────────────────────────────────────────────────────────────────────────
SETUP  (one-time):
─────────────────────────────────────────────────────────────────────────────
  Install Python driver:
      pip install neo4j networkx matplotlib pandas numpy

  Start Neo4j via Docker (easiest):
      docker run -d \
        --name neo4j-fraud \
        -p 7474:7474 -p 7687:7687 \
        -e NEO4J_AUTH=neo4j/frauddetection123 \
        neo4j:latest

  OR download Neo4j Desktop: https://neo4j.com/download/

  Neo4j Browser (optional visual explorer):
      http://localhost:7474

─────────────────────────────────────────────────────────────────────────────
CONFIGURATION  <-- only thing you need to edit:
─────────────────────────────────────────────────────────────────────────────
"""

# ============================================================================
#  USER CONFIGURATION  --  edit these 5 lines, then run the script
# ============================================================================

NEO4J_URI      = "bolt://localhost:7687"
NEO4J_USER     = "neo4j"
NEO4J_PASSWORD = "12345678"          # change to your password

DATASET_PATH   = "synthetic_fraud_graph_dataset.csv"   # input CSV
OUTPUT_DIR     = "."                                    # where to save PNGs

# ============================================================================
#  IMPORTS
# ============================================================================

import os
import time
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import networkx as nx

try:
    from neo4j import GraphDatabase
except ImportError:
    raise SystemExit(
        "\n[ERROR] Neo4j driver missing.\n"
        "Fix:  pip install neo4j\n"
    )

# -- Visual theme -------------------------------------------------------------
DARK    = "#0d1117"
MID     = "#161b22"
PANEL   = "#21262d"
FRAUD   = "#ff4444"
NORMAL  = "#4488ff"
HUB     = "#ffaa00"
DEVICE  = "#aa44ff"
IP_COL  = "#44ffaa"
EDGE_F  = "#ff666688"
EDGE_N  = "#44448844"
WHITE   = "#e6edf3"
GREY    = "#8b949e"

BATCH   = 500


# ============================================================================
#  NEO4J GRAPH CLASS
# ============================================================================

class Neo4jFraudGraph:
    """All Neo4j operations: load, query, extract."""

    def __init__(self, uri, user, password):
        self.driver = GraphDatabase.driver(uri, auth=(user, password))
        print(f"  Neo4j connected  -->  {uri}")

    def close(self):
        self.driver.close()

    def __enter__(self):  return self
    def __exit__(self, *_): self.close()

    def run(self, cypher, params=None):
        with self.driver.session() as s:
            return s.run(cypher, params or {}).data()

    def run_write(self, cypher, params=None):
        with self.driver.session() as s:
            s.execute_write(lambda tx: tx.run(cypher, params or {}))

    # -- schema ---------------------------------------------------------------

    def setup_schema(self):
        print("  Setting up schema ...")
        for c in [
            "CREATE CONSTRAINT account_id IF NOT EXISTS FOR (a:Account) REQUIRE a.account_id IS UNIQUE",
            "CREATE CONSTRAINT device_uid IF NOT EXISTS FOR (d:Device)  REQUIRE d.device_id  IS UNIQUE",
            "CREATE CONSTRAINT ip_addr    IF NOT EXISTS FOR (i:IP)      REQUIRE i.address     IS UNIQUE",
        ]:
            try: self.run_write(c)
            except: pass

    def clear(self):
        print("  Clearing database ...")
        self.run_write("MATCH (n) DETACH DELETE n")

    # -- data loading ---------------------------------------------------------

    def load(self, df: pd.DataFrame):
        """
        INPUT  : pandas DataFrame (your CSV)
        CREATES:
            Nodes         -->  Account, Device, IP
            Relationships -->  SENT_TO, USED_DEVICE, USED_IP
        """
        t0 = time.time()
        print(f"\n  Loading {len(df):,} rows into Neo4j ...")

        # 1. Account nodes
        accts = list(set(df.sender_account) | set(df.receiver_account))
        for i in range(0, len(accts), BATCH):
            self.run_write(
                "UNWIND $b AS r MERGE (:Account {account_id: r.id})",
                {"b": [{"id": a} for a in accts[i:i+BATCH]]})

        # 2. Device nodes
        devs = df.device_id.dropna().unique().tolist()
        for i in range(0, len(devs), BATCH):
            self.run_write(
                "UNWIND $b AS r MERGE (:Device {device_id: r.id})",
                {"b": [{"id": d} for d in devs[i:i+BATCH]]})

        # 3. IP nodes
        ips = df.ip_address.dropna().unique().tolist()
        for i in range(0, len(ips), BATCH):
            self.run_write(
                "UNWIND $b AS r MERGE (:IP {address: r.id})",
                {"b": [{"id": ip} for ip in ips[i:i+BATCH]]})

        # 4. SENT_TO relationships  <-- the transaction edges
        rows = df[["transaction_id","sender_account","receiver_account",
                   "amount","device_id","ip_address",
                   "transaction_type","is_fraud"]].copy()
        rows["timestamp"] = df["timestamp"].astype(str)

        for i in range(0, len(rows), BATCH):
            self.run_write("""
                UNWIND $b AS row
                MATCH (s:Account {account_id: row.sender})
                MATCH (r:Account {account_id: row.receiver})
                CREATE (s)-[t:SENT_TO]->(r)
                SET t.transaction_id = row.txn_id
                SET t.amount           = row.amount,
                    t.timestamp        = row.timestamp,
                    t.device_id        = row.device_id,
                    t.ip_address       = row.ip_address,
                    t.transaction_type = row.txn_type,
                    t.is_fraud         = row.is_fraud
            """, {"b": [
                {"txn_id":   r.transaction_id,
                 "sender":   r.sender_account,
                 "receiver": r.receiver_account,
                 "amount":   float(r.amount),
                 "device_id": r.device_id,
                 "ip_address": r.ip_address,
                 "txn_type":  r.transaction_type,
                 "is_fraud":  int(r.is_fraud),
                 "timestamp": r.timestamp}
                for r in rows.iloc[i:i+BATCH].itertuples()
            ]})

        # 5. USED_DEVICE links
        dev_links = df[["sender_account","device_id"]].drop_duplicates().dropna()
        for i in range(0, len(dev_links), BATCH):
            self.run_write("""
                UNWIND $b AS row
                MATCH (a:Account {account_id: row.src})
                MATCH (d:Device  {device_id:  row.tgt})
                MERGE (a)-[:USED_DEVICE]->(d)
            """, {"b": [{"src": r[0], "tgt": r[1]}
                        for r in dev_links.iloc[i:i+BATCH].itertuples(index=False)]})

        # 6. USED_IP links
        ip_links = df[["sender_account","ip_address"]].drop_duplicates().dropna()
        for i in range(0, len(ip_links), BATCH):
            self.run_write("""
                UNWIND $b AS row
                MATCH (a:Account {account_id: row.src})
                MATCH (ip:IP     {address:    row.tgt})
                MERGE (a)-[:USED_IP]->(ip)
            """, {"b": [{"src": r[0], "tgt": r[1]}
                        for r in ip_links.iloc[i:i+BATCH].itertuples(index=False)]})

        print(f"  Loaded in {time.time()-t0:.1f}s")
        s = self.run("MATCH (n) RETURN labels(n)[0] AS l, count(*) AS c")
        for row in s: print(f"     {row['l']:<12} {row['c']:>7,} nodes")

    # -- fraud queries --------------------------------------------------------

    def query_rings(self):
        """Closed loops on fraud edges: A->B->C->A"""
        return self.run("""
            MATCH path = (a:Account)-[:SENT_TO*3..5]->(a)
            WHERE ALL(r IN relationships(path) WHERE r.is_fraud = 1)
            WITH [n IN nodes(path)[0..-1] | n.account_id] AS members,
                 length(path) AS size,
                 reduce(s=0.0, r IN relationships(path) | s + r.amount) AS total
            RETURN members, size, total
            ORDER BY total DESC LIMIT 30
        """)

    def query_chains(self):
        """Directed mule chains 4-6 hops long."""
        return self.run("""
            MATCH path = (s:Account)-[:SENT_TO*4..6]->(e:Account)
            WHERE ALL(r IN relationships(path) WHERE r.is_fraud = 1)
              AND s <> e
            WITH [n IN nodes(path) | n.account_id]     AS chain,
                 [r IN relationships(path) | r.amount] AS amounts,
                 length(path)                           AS hops,
                 s.account_id AS source, e.account_id AS dest
            RETURN source, dest, chain, amounts, hops
            ORDER BY hops DESC LIMIT 30
        """)

    def query_hubs(self):
        """Accounts receiving fraud transfers from 3+ unique senders."""
        return self.run("""
            MATCH (s:Account)-[t:SENT_TO {is_fraud:1}]->(h:Account)
            WITH h.account_id AS hub,
                 count(DISTINCT s) AS senders,
                 sum(t.amount) AS total,
                 collect(DISTINCT s.account_id)[0..8] AS top_senders
            WHERE senders >= 3
            RETURN hub, senders, total, top_senders
            ORDER BY senders DESC LIMIT 25
        """)

    def query_shared_devices(self):
        """Devices shared by 2+ accounts."""
        return self.run("""
            MATCH (a:Account)-[:USED_DEVICE]->(d:Device)<-[:USED_DEVICE]-(b:Account)
            WHERE a <> b
            WITH d.device_id AS device,
                 collect(DISTINCT a.account_id)[0..10] AS accounts,
                 count(DISTINCT a) AS cnt
            WHERE cnt >= 2
            RETURN device, accounts, cnt
            ORDER BY cnt DESC LIMIT 20
        """)

    def query_risk_scores(self):
        """Composite risk score per account."""
        return self.run("""
            MATCH (a:Account)
            OPTIONAL MATCH (a)-[o:SENT_TO {is_fraud:1}]->()
            OPTIONAL MATCH ()-[i:SENT_TO  {is_fraud:1}]->(a)
            OPTIONAL MATCH (a)-[:USED_DEVICE]->(d:Device)<-[:USED_DEVICE]-(:Account)
            OPTIONAL MATCH (a)-[:USED_IP   ]->(ip:IP   )<-[:USED_IP   ]-(:Account)
            WITH a.account_id      AS account,
                 count(DISTINCT o) AS fraud_sent,
                 count(DISTINCT i) AS fraud_recv,
                 count(DISTINCT d) AS shared_dev,
                 count(DISTINCT ip) AS shared_ip
            WHERE fraud_sent + fraud_recv > 0
            RETURN account, fraud_sent, fraud_recv, shared_dev, shared_ip,
                   (fraud_sent*2 + fraud_recv + shared_dev*3 + shared_ip*2) AS risk_score
            ORDER BY risk_score DESC LIMIT 30
        """)

    def extract_features(self) -> pd.DataFrame:
        """Fast graph feature extraction using Neo4j subqueries."""

        rows = self.run("""
        MATCH (a:Account)

        CALL {
            WITH a
            MATCH (a)-[o:SENT_TO]->()
            RETURN
                count(o) AS out_degree,
                coalesce(sum(o.amount),0) AS total_sent,
                coalesce(avg(o.amount),0) AS avg_sent,
                sum(CASE WHEN o.is_fraud=1 THEN 1 ELSE 0 END) AS fraud_out
        }

        CALL {
            WITH a
            MATCH ()-[i:SENT_TO]->(a)
            RETURN
                count(i) AS in_degree,
                coalesce(sum(i.amount),0) AS total_received,
                sum(CASE WHEN i.is_fraud=1 THEN 1 ELSE 0 END) AS fraud_in
        }

        CALL {
            WITH a
            MATCH (a)-[:USED_DEVICE]->(d:Device)
            RETURN count(DISTINCT d) AS shared_device_count
        }

        CALL {
            WITH a
            MATCH (a)-[:USED_IP]->(ip:IP)
            RETURN count(DISTINCT ip) AS shared_ip_count
        }

        RETURN
            a.account_id AS account_id,
            out_degree,
            in_degree,
            total_sent,
            total_received,
            avg_sent,
            shared_device_count,
            shared_ip_count,
            fraud_out,
            fraud_in,
            (out_degree + in_degree) AS total_degree
        """)

        return pd.DataFrame(rows)


# ============================================================================
#  VISUALISATION FUNCTIONS
#  INPUT  : query results pulled from Neo4j (list of dicts)
#  OUTPUT : PNG saved to OUTPUT_DIR
# ============================================================================

def viz_fraud_rings(rings: list, save_path: str):
    """
    Fraud rings: circular closed-loop subgraphs.
    Each panel = one ring, circular layout.
    """
    if not rings:
        print("  [Viz] No fraud rings to visualise.")
        return

    show  = min(6, len(rings))
    ncols = 3
    nrows = (show + ncols - 1) // ncols
    fig, axes = plt.subplots(nrows, ncols, figsize=(18, nrows*6), facecolor=DARK)
    fig.suptitle("FRAUD RINGS  |  Detected via Neo4j Cypher\n"
                 "Closed money-laundering loops — all edges fraud-labeled",
                 color=WHITE, fontsize=14, fontweight="bold", y=1.01)

    axes = np.array(axes).flatten()
    for idx in range(len(axes)):
        ax = axes[idx]
        ax.set_facecolor(PANEL if idx < show else DARK)
        ax.axis("off")
        if idx >= show:
            continue

        ring    = rings[idx]
        members = ring["members"]
        n       = len(members)
        G       = nx.DiGraph()
        G.add_nodes_from(members)
        for i in range(n):
            G.add_edge(members[i], members[(i+1) % n])

        pos = nx.circular_layout(G)
        nx.draw_networkx_edges(G, pos, ax=ax, edge_color=FRAUD, width=2.5,
                               arrows=True, arrowsize=25,
                               connectionstyle="arc3,rad=0.1",
                               min_source_margin=20, min_target_margin=20)
        nx.draw_networkx_nodes(G, pos, ax=ax, node_color=FRAUD, node_size=900,
                               edgecolors=WHITE, linewidths=1.5)
        nx.draw_networkx_labels(G, pos, ax=ax, font_color=WHITE,
                                font_size=8, font_weight="bold")
        ax.set_title(f"Ring #{idx+1}  |  Size: {ring['size']}  |  "
                     f"Total: ${ring['total']:,.0f}",
                     color=GREY, fontsize=9, pad=8)
        circle = plt.Circle((0, 0), 1.15, fill=False, color=FRAUD,
                             alpha=0.15, lw=2, linestyle="--")
        ax.add_patch(circle)

    plt.tight_layout(pad=2)
    plt.savefig(save_path, dpi=150, bbox_inches="tight", facecolor=DARK)
    plt.close()
    print(f"  Saved  -->  {save_path}")


def viz_mule_chains(chains: list, save_path: str):
    """
    Mule chains: horizontal left-to-right flow diagrams.
    Blue=victim, Orange=mule, Red=final destination.
    """
    if not chains:
        print("  [Viz] No mule chains to visualise.")
        return

    show = min(5, len(chains))
    fig, axes = plt.subplots(show, 1, figsize=(20, show*3.5), facecolor=DARK)
    fig.suptitle("MULE ACCOUNT CHAINS  |  Detected via Neo4j Cypher\n"
                 "Stolen funds flowing through intermediary accounts",
                 color=WHITE, fontsize=14, fontweight="bold")

    if show == 1:
        axes = [axes]

    for idx, ax in enumerate(axes):
        ax.set_facecolor(PANEL)
        ax.axis("off")
        if idx >= show:
            continue

        chain   = chains[idx]
        nodes   = chain["chain"]
        amounts = chain["amounts"]
        n       = len(nodes)

        G   = nx.DiGraph()
        pos = {}
        for i, node in enumerate(nodes):
            G.add_node(node)
            pos[node] = (i / max(n-1, 1), 0.5)
        for i in range(n-1):
            G.add_edge(nodes[i], nodes[i+1])

        source = nodes[0] if nodes else None
        dest   = nodes[-1] if nodes else None
        nodelist = list(G.nodes())
        colors = [
            NORMAL if node == source else FRAUD if node == dest else HUB
            for node in nodelist
        ]

        nx.draw_networkx_edges(G, pos, ax=ax, edge_color=FRAUD, width=3,
                               arrows=True, arrowsize=30,
                               min_source_margin=25, min_target_margin=25)
        nx.draw_networkx_nodes(G, pos, ax=ax, nodelist=nodelist, node_color=colors,
                               node_size=1200, edgecolors=WHITE, linewidths=1.5)
        nx.draw_networkx_labels(G, pos, ax=ax, font_color=WHITE,
                                font_size=7, font_weight="bold")

        edge_labels = {(nodes[i], nodes[i+1]): f"${amounts[i]:,.0f}"
                       for i in range(min(len(amounts), n-1))}
        nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, ax=ax,
                                     font_color=HUB, font_size=8,
                                     bbox=dict(boxstyle="round,pad=0.2",
                                               facecolor=PANEL, alpha=0.8))
        ax.set_title(f"Chain #{idx+1}  |  Hops: {chain['hops']}  |  "
                     f"{chain['source']} --> ... --> {chain['dest']}",
                     color=GREY, fontsize=9)

    legend_patches = [
        mpatches.Patch(color=NORMAL, label="Victim / Source"),
        mpatches.Patch(color=HUB,   label="Intermediary Mule"),
        mpatches.Patch(color=FRAUD, label="Final Destination"),
    ]
    fig.legend(handles=legend_patches, loc="lower center", ncol=3,
               facecolor=PANEL, labelcolor=WHITE, fontsize=9,
               framealpha=0.9, bbox_to_anchor=(0.5, -0.01))

    plt.tight_layout(pad=2)
    plt.savefig(save_path, dpi=150, bbox_inches="tight", facecolor=DARK)
    plt.close()
    print(f"  Saved  -->  {save_path}")


def viz_coordinated_hubs(hubs: list, save_path: str):
    """
    Coordinated hubs: star layout — many senders pointing to one hub.
    """
    if not hubs:
        print("  [Viz] No hubs to visualise.")
        return

    show  = min(6, len(hubs))
    ncols = 3
    nrows = (show + ncols - 1) // ncols
    fig, axes = plt.subplots(nrows, ncols, figsize=(18, nrows*6), facecolor=DARK)
    fig.suptitle("COORDINATED TRANSFER HUBS  |  Detected via Neo4j Cypher\n"
                 "Multiple accounts funneling funds into one central hub",
                 color=WHITE, fontsize=14, fontweight="bold", y=1.01)

    axes = np.array(axes).flatten()
    for idx in range(len(axes)):
        ax = axes[idx]
        ax.set_facecolor(PANEL if idx < show else DARK)
        ax.axis("off")
        if idx >= show:
            continue

        hub     = hubs[idx]
        hub_id  = hub["hub"]
        senders = hub["top_senders"]

        G = nx.DiGraph()
        G.add_node(hub_id)
        G.add_nodes_from(senders)
        for s in senders:
            G.add_edge(s, hub_id)

        pos    = nx.shell_layout(G, nlist=[senders, [hub_id]])
        colors = [HUB if n == hub_id else FRAUD for n in G.nodes()]
        sizes  = [1800 if n == hub_id else 700  for n in G.nodes()]

        nx.draw_networkx_edges(G, pos, ax=ax, edge_color=EDGE_F, width=2,
                               arrows=True, arrowsize=20,
                               min_source_margin=15, min_target_margin=20)
        nx.draw_networkx_nodes(G, pos, ax=ax, node_color=colors,
                               node_size=sizes, edgecolors=WHITE, linewidths=1.2)
        nx.draw_networkx_labels(G, pos, ax=ax, font_color=WHITE,
                                font_size=7, font_weight="bold")
        ax.set_title(f"Hub #{idx+1}: {hub_id}\n"
                     f"Senders: {hub['senders']}  |  Total: ${hub['total']:,.0f}",
                     color=GREY, fontsize=9)

    legend_patches = [
        mpatches.Patch(color=HUB,   label="Hub (receiver)"),
        mpatches.Patch(color=FRAUD, label="Sender accounts"),
    ]
    fig.legend(handles=legend_patches, loc="lower center", ncol=2,
               facecolor=PANEL, labelcolor=WHITE, fontsize=9,
               bbox_to_anchor=(0.5, -0.01))
    plt.tight_layout(pad=2)
    plt.savefig(save_path, dpi=150, bbox_inches="tight", facecolor=DARK)
    plt.close()
    print(f"  Saved  -->  {save_path}")


def viz_shared_devices(device_clusters: list, save_path: str):
    """
    Shared device clusters: device node at centre, accounts around it.
    """
    if not device_clusters:
        print("  [Viz] No device clusters to visualise.")
        return

    show  = min(6, len(device_clusters))
    ncols = 3
    nrows = (show + ncols - 1) // ncols
    fig, axes = plt.subplots(nrows, ncols, figsize=(18, nrows*5), facecolor=DARK)
    fig.suptitle("SHARED DEVICE CLUSTERS  |  Detected via Neo4j Cypher\n"
                 "Same device used by multiple accounts -- compromised infrastructure",
                 color=WHITE, fontsize=14, fontweight="bold", y=1.01)

    axes = np.array(axes).flatten()
    for idx in range(len(axes)):
        ax = axes[idx]
        ax.set_facecolor(PANEL if idx < show else DARK)
        ax.axis("off")
        if idx >= show:
            continue

        cluster  = device_clusters[idx]
        dev_id   = cluster["device"]
        accounts = cluster["accounts"]

        G = nx.Graph()
        G.add_node(dev_id, kind="device")
        for a in accounts:
            G.add_node(a, kind="account")
            G.add_edge(dev_id, a)

        # Use shell_layout as a star-like fallback (no star_layout in NetworkX)
        pos    = nx.shell_layout(G, nlist=[[dev_id], accounts])
        nodelist = list(G.nodes())
        colors = [DEVICE if G.nodes[n].get("kind") == "device"
                  else FRAUD for n in nodelist]
        sizes  = [1500 if G.nodes[n].get("kind") == "device"
                  else 600 for n in nodelist]

        nx.draw_networkx_edges(G, pos, ax=ax, edge_color=DEVICE+"88", width=1.8)
        nx.draw_networkx_nodes(G, pos, ax=ax, nodelist=nodelist, node_color=colors,
                               node_size=sizes, edgecolors=WHITE, linewidths=1)
        nx.draw_networkx_labels(G, pos, ax=ax, font_color=WHITE,
                                font_size=7, font_weight="bold")
        ax.set_title(f"Device: {dev_id[:20]}\nShared by {cluster['cnt']} accounts",
                     color=GREY, fontsize=9)

    legend_patches = [
        mpatches.Patch(color=DEVICE, label="Shared Device"),
        mpatches.Patch(color=FRAUD,  label="Account using device"),
    ]
    fig.legend(handles=legend_patches, loc="lower center", ncol=2,
               facecolor=PANEL, labelcolor=WHITE, fontsize=9,
               bbox_to_anchor=(0.5, -0.01))
    plt.tight_layout(pad=2)
    plt.savefig(save_path, dpi=150, bbox_inches="tight", facecolor=DARK)
    plt.close()
    print(f"  Saved  -->  {save_path}")


def viz_risk_scores(risk_rows: list, save_path: str):
    """
    Risk score dashboard: horizontal bar chart + stacked signal breakdown.
    """
    if not risk_rows:
        print("  [Viz] No risk scores to visualise.")
        return

    df = pd.DataFrame(risk_rows).head(20).sort_values("risk_score")

    fig, axes = plt.subplots(1, 2, figsize=(18, 8), facecolor=DARK)
    fig.suptitle("HIGH-RISK ACCOUNT SCORING  |  Graph Features from Neo4j",
                 color=WHITE, fontsize=14, fontweight="bold")

    ax = axes[0]
    ax.set_facecolor(PANEL)
    colors = [FRAUD if s >= df["risk_score"].quantile(0.75)
              else HUB if s >= df["risk_score"].quantile(0.5)
              else NORMAL for s in df["risk_score"]]
    bars = ax.barh(df["account"], df["risk_score"],
                   color=colors, edgecolor="#ffffff11", height=0.7)
    for bar, val in zip(bars, df["risk_score"]):
        ax.text(val + 0.2, bar.get_y() + bar.get_height()/2,
                f"{val:.0f}", va="center", color=WHITE, fontsize=8)
    ax.set_xlabel("Composite Risk Score", color=GREY, fontsize=9)
    ax.set_title("Top Accounts by Risk Score", color=WHITE, fontsize=11)
    ax.tick_params(colors=GREY, labelsize=8)
    for sp in ax.spines.values(): sp.set_edgecolor("#333344")

    ax2 = axes[1]
    ax2.set_facecolor(PANEL)
    x = np.arange(len(df))
    ax2.barh(x, df["fraud_sent"], 0.6, label="Fraud Sent",     color=FRAUD,  alpha=0.9)
    ax2.barh(x, df["fraud_recv"], 0.6, left=df["fraud_sent"],
             label="Fraud Received", color=HUB, alpha=0.9)
    ax2.barh(x, df["shared_dev"], 0.6,
             left=df["fraud_sent"]+df["fraud_recv"],
             label="Shared Devices", color=DEVICE, alpha=0.9)
    ax2.set_yticks(x)
    ax2.set_yticklabels(df["account"], fontsize=8, color=GREY)
    ax2.set_xlabel("Signal Counts", color=GREY, fontsize=9)
    ax2.set_title("Risk Signal Breakdown", color=WHITE, fontsize=11)
    ax2.legend(facecolor=MID, labelcolor=WHITE, fontsize=8, loc="lower right")
    ax2.tick_params(colors=GREY, labelsize=8)
    for sp in ax2.spines.values(): sp.set_edgecolor("#333344")

    plt.tight_layout(pad=2)
    plt.savefig(save_path, dpi=150, bbox_inches="tight", facecolor=DARK)
    plt.close()
    print(f"  Saved  -->  {save_path}")


def viz_full_network(rings, chains, hubs, save_path: str):
    """
    Combined fraud network: all three pattern types on one graph.
    Color-coded by pattern type.
    """
    G          = nx.DiGraph()
    node_type  = {}
    edge_type  = {}

    for ring in rings[:4]:
        m = ring["members"]
        for node in m:
            G.add_node(node)
            node_type.setdefault(node, "ring")
        for i in range(len(m)):
            u, v = m[i], m[(i+1) % len(m)]
            G.add_edge(u, v)
            edge_type[(u, v)] = "ring"

    for chain in chains[:4]:
        c = chain["chain"]
        for node in c:
            G.add_node(node)
            node_type.setdefault(node, "chain")
        for i in range(len(c)-1):
            G.add_edge(c[i], c[i+1])
            edge_type[(c[i], c[i+1])] = "chain"

    for hub in hubs[:4]:
        G.add_node(hub["hub"])
        node_type.setdefault(hub["hub"], "hub")
        for s in hub["top_senders"][:5]:
            G.add_node(s)
            node_type.setdefault(s, "sender")
            G.add_edge(s, hub["hub"])
            edge_type[(s, hub["hub"])] = "hub"

    if G.number_of_nodes() == 0:
        print("  [Viz] Not enough data for combined network view.")
        return

    fig, ax = plt.subplots(figsize=(20, 16), facecolor=DARK)
    ax.set_facecolor(DARK)
    ax.axis("off")
    fig.suptitle("COMBINED FRAUD NETWORK  |  All Patterns from Neo4j\n"
                 "Red=Fraud Ring  |  Orange=Mule Chain  |  Yellow=Hub  |  Blue=Sender",
                 color=WHITE, fontsize=14, fontweight="bold")

    pos = nx.spring_layout(G, seed=42, k=1.8)

    type_color  = {"ring": FRAUD, "chain": HUB,   "hub": "#ffdd00", "sender": NORMAL}
    type_size   = {"ring": 800,   "chain": 700,   "hub": 1400,      "sender": 500}
    etype_color = {"ring": FRAUD, "chain": HUB+"aa", "hub": "#ffdd0088"}

    ncolors = [type_color.get(node_type.get(n, "sender"), GREY) for n in G.nodes()]
    nsizes  = [type_size .get(node_type.get(n, "sender"), 500)  for n in G.nodes()]
    ecolors = [etype_color.get(edge_type.get((u,v), "hub"), GREY)
               for u, v in G.edges()]

    nx.draw_networkx_edges(G, pos, ax=ax, edge_color=ecolors, width=1.8,
                           arrows=True, arrowsize=15,
                           connectionstyle="arc3,rad=0.1",
                           min_source_margin=12, min_target_margin=12)
    nx.draw_networkx_nodes(G, pos, ax=ax, node_color=ncolors,
                           node_size=nsizes, edgecolors=WHITE, linewidths=0.8)
    nx.draw_networkx_labels(G, pos, ax=ax, font_color=WHITE,
                            font_size=6, font_weight="bold")

    legend_patches = [
        mpatches.Patch(color=FRAUD,    label="Fraud Ring node"),
        mpatches.Patch(color=HUB,      label="Mule Chain node"),
        mpatches.Patch(color="#ffdd00",label="Hub (coordinator)"),
        mpatches.Patch(color=NORMAL,   label="Sender account"),
    ]
    ax.legend(handles=legend_patches, loc="lower left",
              facecolor=PANEL, labelcolor=WHITE, fontsize=10, framealpha=0.9)
    ax.text(0.99, 0.01,
            f"Nodes: {G.number_of_nodes()}  |  Edges: {G.number_of_edges()}",
            transform=ax.transAxes, color=GREY, fontsize=9, ha="right")

    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight", facecolor=DARK)
    plt.close()
    print(f"  Saved  -->  {save_path}")


# ============================================================================
#  MAIN PIPELINE
# ============================================================================

def main():
    print("=" * 65)
    print("  Autonomous Fraud Detection & Response Network")
    print("  Neo4j Pipeline  +  Python Visualisation")
    print("=" * 65)
    print()
    print("  INPUT  : " + DATASET_PATH)
    print("  OUTPUT : " + OUTPUT_DIR)
    print("  NEO4J  : " + NEO4J_URI)
    print()

    # Step 1: Load CSV
    print("[1] Reading input CSV ...")
    try:
        df = pd.read_csv(DATASET_PATH, parse_dates=["timestamp"])
    except FileNotFoundError:
        raise SystemExit(
            f"\n[ERROR] File not found: {DATASET_PATH}\n"
            "Run generate_fraud_dataset.py first.\n"
        )
    print(f"  Rows  : {len(df):,}")
    print(f"  Fraud : {df['is_fraud'].sum():,} ({df['is_fraud'].mean()*100:.1f}%)")

    # Step 2: Neo4j - load and query
    print("\n[2] Connecting to Neo4j and loading graph ...")
    try:
        with Neo4jFraudGraph(NEO4J_URI, NEO4J_USER, NEO4J_PASSWORD) as g:
            g.clear()
            g.setup_schema()
            g.load(df)

            print("\n[3] Running fraud detection queries ...")
            rings   = g.query_rings()
            chains  = g.query_chains()
            hubs    = g.query_hubs()
            devices = g.query_shared_devices()
            risk    = g.query_risk_scores()
            print(f"  Rings: {len(rings)}  Chains: {len(chains)}  "
                  f"Hubs: {len(hubs)}  Devices: {len(devices)}")

            print("\n[4] Extracting graph features for ML ...")
            feat_df  = g.extract_features()
            enriched = df.merge(
                feat_df.rename(columns={"account_id": "sender_account"}),
                on="sender_account", how="left")
            out_csv = os.path.join(OUTPUT_DIR, "neo4j_enriched_fraud_dataset.csv")
            enriched.to_csv(out_csv, index=False)
            print(f"  Saved --> {out_csv}")

    except Exception as e:
        print(f"\n[ERROR] Neo4j: {e}")
        print("\n  Start Neo4j with Docker:")
        print("    docker run -d --name neo4j-fraud \\")
        print("      -p 7474:7474 -p 7687:7687 \\")
        print("      -e NEO4J_AUTH=neo4j/frauddetection123 \\")
        print("      neo4j:latest\n")
        raise

    # Step 3: Generate all visualisations
    print("\n[5] Generating visualisations ...")
    p = lambda name: os.path.join(OUTPUT_DIR, name)
    viz_fraud_rings      (rings,   p("viz_fraud_rings.png"))
    viz_mule_chains      (chains,  p("viz_mule_chains.png"))
    viz_coordinated_hubs (hubs,    p("viz_coordinated_hubs.png"))
    viz_shared_devices   (devices, p("viz_shared_devices.png"))
    viz_risk_scores      (risk,    p("viz_risk_scores.png"))
    viz_full_network     (rings, chains, hubs, p("viz_full_fraud_network.png"))

    # Summary
    print("\n" + "=" * 65)
    print("  COMPLETE")
    print("=" * 65)
    print(f"  Fraud rings detected      : {len(rings)}")
    print(f"  Mule chains detected      : {len(chains)}")
    print(f"  Coordinated hubs found    : {len(hubs)}")
    print(f"  Shared device clusters    : {len(devices)}")
    print(f"  High-risk accounts scored : {len(risk)}")
    print()
    print("  Files saved:")
    for f in ["neo4j_enriched_fraud_dataset.csv",
              "viz_fraud_rings.png", "viz_mule_chains.png",
              "viz_coordinated_hubs.png", "viz_shared_devices.png",
              "viz_risk_scores.png", "viz_full_fraud_network.png"]:
        print(f"    {f}")
    print()
    print("  Neo4j Browser (interactive graphs): http://localhost:7474")
    print("=" * 65)
    print("\n  Done.\n")


if __name__ == "__main__":
    main()
